// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/srv/srv.proto

package go_micro_service_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Srv service

type SrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Srv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Srv_PingPongService, error)
}

type srvService struct {
	c    client.Client
	name string
}

func NewSrvService(name string, c client.Client) SrvService {
	return &srvService{
		c:    c,
		name: name,
	}
}

func (c *srvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Srv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Srv_StreamService, error) {
	req := c.c.NewRequest(c.name, "Srv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &srvServiceStream{stream}, nil
}

type Srv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type srvServiceStream struct {
	stream client.Stream
}

func (x *srvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *srvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *srvService) PingPong(ctx context.Context, opts ...client.CallOption) (Srv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Srv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &srvServicePingPong{stream}, nil
}

type Srv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type srvServicePingPong struct {
	stream client.Stream
}

func (x *srvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *srvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *srvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *srvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Srv service

type SrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Srv_StreamStream) error
	PingPong(context.Context, Srv_PingPongStream) error
}

func RegisterSrvHandler(s server.Server, hdlr SrvHandler, opts ...server.HandlerOption) error {
	type srv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Srv struct {
		srv
	}
	h := &srvHandler{hdlr}
	return s.Handle(s.NewHandler(&Srv{h}, opts...))
}

type srvHandler struct {
	SrvHandler
}

func (h *srvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SrvHandler.Call(ctx, in, out)
}

func (h *srvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SrvHandler.Stream(ctx, m, &srvStreamStream{stream})
}

type Srv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type srvStreamStream struct {
	stream server.Stream
}

func (x *srvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *srvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *srvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SrvHandler.PingPong(ctx, &srvPingPongStream{stream})
}

type Srv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type srvPingPongStream struct {
	stream server.Stream
}

func (x *srvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *srvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *srvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
